void FMLSRawMaterialVisibilityOverlay::UpdateCapabilityReceipt(const FString& OverlayDir)
{
	// The runtime capability manifest is generated by the primary patcher.
	// Keep this post-patch side-effect free; the visual/build acceptance log is
	// the source of truth for the v0.15 overlay-only sample-occlusion transport.
	(void)OverlayDir;
}
